### ISSUE TITLE
v2 update really not updated?

### ISSUE THREAD

**Issue by tcreek** [ladybirdweb/faveo-probe#28]
I downloaded v2.0 and expanded archive into directory faveo-probe-2.0

 As you can see in the image it is showing version 1.0, and reporting

>  Error! Minimum PHP version required in order to run Faveo is PHP 5.5.*

I have PHP 7.2 installed.

 php --version
```
PHP 7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b (cli) (built: May 31 2019 11:26:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b, Copyright (c) 1999-2018, by Zend Technologies

```

![faveo-probe](https://user-images.githubusercontent.com/4149717/60200528-e412a480-980b-11e9-9176-ee9b7a2298a2.jpg)

**Comment by kreatorcodes** [comment]
@tcreek the screenshot you shared shows "Probe version:1.0", I am not sure you the zip archive you extracted actually contains v2.0. Can you share the downloaded file and the extracted folder's content with me at manish.verma@ladybirdweb.com

**Comment by tcreek** [comment]
Responded, but your mail system is not allowing . I have added it here

<manish.verma@ladybirdweb.com>: host alt2.aspmx.l.google.com[64.233.176.26]
    said: 552-5.7.0 This message was blocked because its content presents a
    potential 552-5.7.0 security issue. Please visit 552-5.7.0
    https://support.google.com/mail/?p=BlockedMessage to review our 552 5.7.0
    message content and attachment content guidelines. g83si221027ywc.216 -
    gsmtp (in reply to end of DATA command)

[faveo-probe-2.0.tar.gz](https://github.com/ladybirdweb/faveo-probe/files/3334615/faveo-probe-2.0.tar.gz)

**Comment by mverma16** [comment]
share your email I'll share the dropbox link where you can share the files.

**Comment by kreatorcodes** [comment]
Tried in my system extracting the file you shared it shows the correct information. Can you share the content step1.php file which you are running on the server? Also please share the server environment as in the error you got it should show PHP version running on the server.
 
![Screenshot 2019-06-27 at 6 07 35 PM](https://user-images.githubusercontent.com/10759797/60266838-8616b780-9906-11e9-9666-338c1dcf5bb7.png)

**Comment by tcreek** [comment]
I see the problem now.   The actual index.php file is the culprit that has not been fully updated as we can see starting on line 37

 
```
     <strong>Probe Version:</strong> 1.0
                <br><strong>Testing For:</strong> Faveo HELPDESK 1.0.6 and Newer</p>
                 <div class="woocommerce-message woocommerce-tracker "><p><span id="fail">Error!</span> Minimum PHP version required in$
```

        
I had been accessing index.php directly in the browser on a system which was slightly misconfigured, causing the issue.

I started fresh again, and all is good now.

Thanks for the responses

**Comment by kreatorcodes** [comment]
@tcreek thanks for reporting, we will update index.php for the same.
